### ISSUE TITLE
Unable to generate simple plural phrase

### ISSUE THREAD

**Issue by maguro** [localizely/flutter-intl-intellij#15]
For en

    "Password must be longer than {howMany, plural, one{one character} other{{howMany} characters}}"

and es

    "La contraseña debe tener más de {howMany, plural, one{un carácter} other{{howMany} caracteres}}"

Generation fails with parsing errors.

**Comment by aleksakrstic** [comment]
Hi @maguro 
The plugin supports strings that are complete plurals.
Does not support mix of regular string and plural parts, due to its complexity for different variations.

So in your case, you can write given translations like:
For `en`:
`"{howMany, plural, one{Password must be longer than one character} other{Password must be longer than {howMany} characters}}"`
For `es`:
`"{howMany, plural, one{La contraseña debe tener más de un carácter} other{La contraseña debe tener más de {howMany} caracteres}}"`

Hope this helps.

**Comment by maguro** [comment]
That workaround worked.  Are there any plans on supporting mix of regular string and plural parts?  Looking forward to seeing the project open sourced.

**Comment by aleksakrstic** [comment]
@maguro 
No plans for now to support regular-plural mix within the same translations.
Maybe in the future if there is a high demand.

**Comment by maguro** [comment]
Happy to help once source gets released...
