### ISSUE TITLE
mouse-over and show translation

### ISSUE THREAD

**Issue by shinriyo** [localizely/flutter-intl-intellij#24]
hello. it is a good plugin.
I want see translation while doing mouse-over the variable.

**Comment by aleksakrstic** [comment]
Hi @shinriyo 
We plan to show translation via Quick Documentation Lookup shortcut (ctrl+J on Mac, ctrl+Q on Windows).

<img width="542" alt="Screenshot 2020-05-18 at 15 50 30" src="https://user-images.githubusercontent.com/59895497/82221119-da13fb80-991f-11ea-805e-835088de84a2.png">

Is that what you mean?
Since I don't see practices in IntelliJ / Android Studio to show some info on mouse hover action

**Comment by shinriyo** [comment]
@aleksakrstic Yes exactly I mean.
Is it plan? So, it didn't implemented yet?
Why did you choose "J"?
And, can the future show all of translations?

**Comment by aleksakrstic** [comment]
@shinriyo 
It is in the plan for a future release.

ctrl + J is a default shortcut for Quick doc lookup: https://www.jetbrains.com/help/rider/Keymaps_Comparison_Mac.html

It will show only main translation

**Comment by aleksakrstic** [comment]
@shinriyo 
This is now available in version 1.8.0.
