### ISSUE TITLE
Support settings for translations download.

### ISSUE THREAD

**Issue by kirimi** [localizely/flutter-intl-intellij#43]
In https://app.localizely.com we have options for empty transtations download:
* export as empty string
* don't export
* export with main language

As I found, the plugin behaviour is only 'export as empty string'.

Could you please add possibility to download translations with '**export with main language**' option?

**Comment by lzoran** [comment]
Hi @kirimi,

Thanks for reporting this issue!

The download configuration is supported since Flutter Intl 1.11.0, but it seems that documentation is not updated yet (it will be fixed soon).

To configure how empty translations should be exported from the Localizely, you can use `download_empty_as` config parameter within `pubspec.yaml` file (check example below).
```
flutter_intl:
  ...
  localizely: 
    ...
    download_empty_as: main # Set to empty|main|skip, to configure how empty translations should be exported from the Localizely platform. Default: empty
```

**Comment by kirimi** [comment]
@lzoran perfect! Thank you!
