### ISSUE TITLE
Wrong generated plurals

### ISSUE THREAD

**Issue by m-ochyra** [localizely/flutter-intl-intellij#55]
Hi,
I have a problem with plurals generated by this plugin. Problem is about generating arguments. Let me show it on an example.

I have english message:
`"{howMany, plural, one{1 week} other{{howMany} weeks}}"`
and generated result is OK:
```dart
static m1(howMany) => "${Intl.plural(howMany, one: '1 week', other: '${howMany} weeks')}";
```

Problem is in polish version of this message:
`"{howMany, plural, one{1 tydzień} few{{howMany} tygodnie}} other{{howMany} tygodni}}"`
and in this case generated result have missing `other` param:
```dart
static m1(howMany) => "${Intl.plural(howMany, one: '1 tydzień', few: '${howMany} tygodnie')}";
```

This generate this error:
`Invalid argument(s): The 'other' named argument must be provided`

"Almost" working solution is changing order of `few` and `other` params, but in this case a `few` param is missing:
`"{howMany, plural, one{1 tydzień} other{{howMany} tygodni}} few{{howMany} tygodnie}}"`
and this is result:
```dart
static m1(howMany) => "${Intl.plural(howMany, one: '1 tydzień', other: '${howMany} tygodni')}";
```

When I change english message to:
`"{howMany, plural, one {1 week} few {{howMany} weeks}} other {{howMany} weeks}}"`
result is:
```dart
static m1(howMany) => "${Intl.plural(howMany, one: '1 week', few: '${howMany} weeks')}";
```
with warning in the console:
`WARNING: The 'weeksFormat' key lacks mandatory plural form 'other'.`

Is this plugin working only with two params or I make some mistake?

Thank you for help.

**Comment by lzoran** [comment]
Hi @m-ochyra,

Thanks for reporting this!

The plugin should work with all plural forms within the plural message.
I believe that the problem here is with the additional closing curly bracket.

Examples:
`"{howMany, plural, one{1 tydzień} few{{howMany} tygodnie}} other{{howMany} tygodni}}"` ❌
`"{howMany, plural, one{1 tydzień} few{{howMany} tygodnie} other{{howMany} tygodni}}"` ✔️

`"{howMany, plural, one{1 tydzień} other{{howMany} tygodni}} few{{howMany} tygodnie}}"` ❌
`"{howMany, plural, one{1 tydzień} other{{howMany} tygodni} few{{howMany} tygodnie}}"` ✔️

`"{howMany, plural, one {1 week} few {{howMany} weeks}} other {{howMany} weeks}}"` ❌
`"{howMany, plural, one {1 week} few {{howMany} weeks} other {{howMany} weeks}}"` ✔️

**Comment by m-ochyra** [comment]
Hi @lzoran!

Thank you very much for your help. Indeed, I was adding an extra closing curly bracket unnecessarily. Now all is good.
