### ISSUE TITLE
How to specific locale in one statement without reloading locale for entire app

### ISSUE THREAD

**Issue by narumishi** [localizely/flutter-intl-intellij#56]
Suppose such a situation, I want to generate a dict. Its keys always be English and values should respond to localization.
We cannot call `S.load()` to specific locale for keys here. I looked into generated codes, but still have no idea.

Supposed ways to get specific values could be 
- `S.ofLocale(Locale('en')).hello`
- `S.en.hello`

Any idea about how to achieve this?

**Comment by lzoran** [comment]
Hi @narumishi,

You are right. Multiple localizations at the same time is not yet supported - [issue](https://github.com/localizely/flutter-intl-intellij/issues/26). There is a [PR](https://github.com/localizely/intl_utils/pull/18) that solves this issue. Unfortunately, it introduces a breaking change for existing users.

Regarding the dict you want to generate, does the usage of ICU Select work for you?

ICU Select example:
```
"commonLanguage": "{localeCode, select, en {English} de {Deutsche} es {Español} other {Unknown}}",
"@commonLanguage": {
  "description": "Localized language names",
  "placeholders": {
    "localeCode": {}
  }
}
```

Usage example:
```
Text(S.of(context).commonLanguage('en'))
```

**Comment by narumishi** [comment]
@lzoran Thanks for your quick reply.

ICU select is a choice, but I need to combine all localized strings into main locale's arb file. And I need to pass language code every time even for default current locale, like `S.of(context).commonLanguage(Intl.getCurrentLocale())`.

Did your team consider merge that PR into a new branch?  So that we can directly use it from that branch of git repo, without effects on existing users.

**Comment by aleksakrstic** [comment]
Hi @narumishi, this issue seems the same as this one https://github.com/localizely/flutter-intl-intellij/issues/26, correct me if I misunderstood it.

Regarding mentioned PR, it is still early to merge it. Wouldn't create a separate branch for it since it might create a different paths for the package which would be hard to manage. You can always fork given PR changes and manage it on your own, if you really need it.

Closing this issue as a duplicate.
